'use client';
import {AnimatePresence,motion} from 'framer-motion';import {useState} from 'react';import Image from 'next/image';import Link from 'next/link';import {X,Plus,Minus} from 'lucide-react';import {useStore} from './Store';import {inr,FREE_SHIPPING} from '@/lib/shopify';
export default function CartDrawer(){const {cart,open,setOpen,busy,setQty,remove,applyCode}=useStore(),[code,setCode]=useState(''),sub=Number(cart?.cost.subtotalAmount.amount??0),left=Math.max(0,FREE_SHIPPING-sub),lines=cart?.lines.nodes??[];
return <AnimatePresence>{open&&<><motion.div className="fixed inset-0 bg-black/60 z-[80]" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setOpen(false)}/>
<motion.aside role="dialog" aria-label="Bag" className="fixed right-0 inset-y-0 w-full max-w-md bg-ink z-[90] flex flex-col p-6" initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} transition={{duration:.6,ease:[.16,1,.3,1]}}>
<div className="flex justify-between items-center pb-4 border-b border-bone/15"><h2 className="dsp text-4xl">Your bag</h2><button aria-label="Close" onClick={()=>setOpen(false)}><X/></button></div>
<div className="flex-1 overflow-auto py-2">{lines.length===0?<div className="text-center py-16"><h3 className="dsp text-6xl mb-6">Your bag is<br/>too quiet.</h3><Link href="/shop" onClick={()=>setOpen(false)} className="btn">Start shopping →</Link></div>
:lines.map(l=><div key={l.id} className="grid grid-cols-[72px_1fr_auto] gap-3 py-4 border-b border-bone/15">
<div className="relative aspect-[4/5] bg-char">{l.merchandise.image&&<Image src={l.merchandise.image.url} alt="" fill sizes="72px" className="object-cover"/>}</div>
<div><Link href={`/product/${l.merchandise.product.handle}`} onClick={()=>setOpen(false)}>{l.merchandise.product.title}</Link><p className="text-bone/60 text-sm">{l.merchandise.title}</p>
<div className="inline-flex items-center gap-3 border border-bone/15 mt-2 px-2"><button aria-label="Less" disabled={busy} onClick={()=>setQty(l.id,l.quantity-1)}><Minus size={14}/></button>{l.quantity}<button aria-label="More" disabled={busy} onClick={()=>setQty(l.id,l.quantity+1)}><Plus size={14}/></button></div></div>
<div className="text-right"><b>{inr(Number(l.merchandise.price.amount)*l.quantity)}</b><br/><button className="lab underline text-bone/60" onClick={()=>remove(l.id)}>Remove</button></div></div>)}</div>
{lines.length>0&&<div className="border-t border-bone/15 pt-4"><p className="lab">{left?`${inr(left)} away from free shipping`:'Free shipping unlocked'}</p><div className="h-1 bg-bone/15 my-2 mb-4"><div className="h-full bg-acid transition-all duration-700 ease-lf" style={{width:`${Math.min(100,sub/FREE_SHIPPING*100)}%`}}/></div>
<form onSubmit={e=>{e.preventDefault();applyCode(code.trim())}} className="flex gap-2 mb-3"><input value={code} onChange={e=>setCode(e.target.value)} placeholder="Discount code" aria-label="Discount code" className="flex-1 bg-transparent border border-bone/15 px-3 py-2 outline-none focus:border-acid"/><button className="lab border border-bone px-4">Apply</button></form>{cart!.discountCodes?.some(d=>!d.applicable)&&<p className="text-red-400 text-sm mb-2" role="alert">That code isn't valid.</p>}{cart!.discountCodes?.some(d=>d.applicable)&&<p className="text-acid text-sm mb-2">Code applied — final price at checkout.</p>}<div className="flex justify-between mb-3"><span className="lab">Subtotal</span><b>{inr(sub)}</b></div><a href={cart!.checkoutUrl} className="btn w-full py-5 text-base">Checkout →</a></div>}
</motion.aside></>}</AnimatePresence>}
