'use client';
import {useCallback,useEffect,useState} from 'react';import Image from 'next/image';import {AnimatePresence,motion} from 'framer-motion';import Reveal from './Reveal';
export type Look={title:string;src:string;alt:string;color:string};
const SPAN=['col-span-12 md:col-span-7 row-span-3','col-span-6 md:col-span-5 row-span-2','col-span-6 md:col-span-5 row-span-2','col-span-6 md:col-span-4 row-span-2','col-span-12 md:col-span-8 row-span-2','col-span-6 md:col-span-3 row-span-3','col-span-6 md:col-span-5 row-span-2','col-span-12 md:col-span-4 row-span-2'];
const Frame=({l,fill=false}:{l:Look;fill?:boolean})=><div className="absolute inset-0 flex items-end p-4" style={{background:l.color,color:'#050505'}}>{l.src?<Image src={l.src} alt={l.alt} fill sizes="(max-width:768px) 100vw,60vw" className="object-cover"/>:<span className={`dsp ${fill?'text-7xl':'text-4xl'} opacity-85`}>{l.title}</span>}</div>;
export default function Lookbook({items}:{items:Look[]}){const [i,setI]=useState<number|null>(null),N=items.length,go=useCallback((d:number)=>setI(x=>x===null?x:(x+d+N)%N),[N]);
useEffect(()=>{if(i===null)return;const k=(e:KeyboardEvent)=>{if(e.key==='Escape')setI(null);if(e.key==='ArrowRight')go(1);if(e.key==='ArrowLeft')go(-1)};addEventListener('keydown',k);document.body.style.overflow='hidden';return()=>{removeEventListener('keydown',k);document.body.style.overflow=''}},[i,go]);
return <main className="pt-10 px-4 md:px-10 pb-24"><h1 className="dsp text-[clamp(64px,13vw,210px)] pb-2">Lookbook</h1><p className="lab text-fg/70 mb-8">Select any frame to open the gallery</p>
<div className="grid grid-cols-12 auto-rows-[110px] md:auto-rows-[clamp(120px,17vw,250px)] gap-2 md:gap-4">{items.map((l,n)=><Reveal key={n} d={(n%3)*.08} className={`relative ${SPAN[n%SPAN.length]}`}><button data-cursor="EXPLORE" onClick={()=>setI(n)} aria-label={`Open ${l.title||l.alt}`} className="absolute inset-0 w-full overflow-hidden transition duration-700 ease-lf hover:scale-[.985]"><Frame l={l}/></button></Reveal>)}</div>
<AnimatePresence>{i!==null&&<motion.div role="dialog" aria-modal="true" aria-label="Lookbook gallery" className="fixed inset-0 z-[100] bg-surface grid grid-rows-[auto_1fr_auto]" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}>
<div className="flex justify-between p-5 lab"><span>{String(i+1).padStart(2,'0')} / {String(N).padStart(2,'0')}</span><button onClick={()=>setI(null)}>Close ✕</button></div>
<motion.div key={i} drag="x" dragConstraints={{left:0,right:0}} onDragEnd={(_,f)=>{if(f.offset.x<-60)go(1);if(f.offset.x>60)go(-1)}} initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} transition={{duration:.5,ease:[.16,1,.3,1]}} className="relative mx-auto w-[min(560px,92vw)] aspect-[4/5] self-center"><Frame l={items[i]} fill/></motion.div>
<div className="flex justify-between p-5 lab"><button onClick={()=>go(-1)}>← Prev</button><span>{items[i].title}</span><button onClick={()=>go(1)}>Next →</button></div></motion.div>}</AnimatePresence></main>}
