'use client';
import {useCallback,useEffect,useState} from 'react';import Image from 'next/image';import {AnimatePresence,motion} from 'framer-motion';import Reveal from './Reveal';import {ASSETS} from '@/lib/assets';
// Replace `src` with your photos, e.g. '/lookbook/01.jpg' (put files in /public/lookbook)
export const LOOKS=[{t:'After Dark',c:'#D8D5CE',src:''},{t:'Wrong Lane',c:'#C6FF00',src:''},{t:'Heavyweight',c:'#2B4BFF',src:''},{t:'Off-White',c:'#F4F1EA',src:''},{t:'Blood Red',c:'#B0121B',src:''},{t:'Detail',c:'#D8D5CE',src:''},{t:'Street',c:'#C6FF00',src:''},{t:'Freak Mode',c:'#F4F1EA',src:''}];
LOOKS.forEach((l,i)=>{l.src=ASSETS.look[i]||l.src});
const SPAN=['col-span-12 md:col-span-7 row-span-3','col-span-6 md:col-span-5 row-span-2','col-span-6 md:col-span-5 row-span-2','col-span-6 md:col-span-4 row-span-2','col-span-12 md:col-span-8 row-span-2','col-span-6 md:col-span-3 row-span-3','col-span-6 md:col-span-5 row-span-2','col-span-12 md:col-span-4 row-span-2'];
const Frame=({l,fill=false}:{l:typeof LOOKS[0];fill?:boolean})=><div className="absolute inset-0 flex items-end p-4" style={{background:l.c,color:'#050505'}}>{l.src&&<Image src={l.src} alt={l.t} fill sizes="(max-width:768px) 100vw,60vw" className="object-cover"/>}{!l.src&&<span className={`dsp ${fill?'text-7xl':'text-4xl'} opacity-85`}>{l.t}</span>}</div>;
export default function Lookbook(){const [i,setI]=useState<number|null>(null),go=useCallback((d:number)=>setI(x=>x===null?x:(x+d+LOOKS.length)%LOOKS.length),[]);
useEffect(()=>{if(i===null)return;const k=(e:KeyboardEvent)=>{if(e.key==='Escape')setI(null);if(e.key==='ArrowRight')go(1);if(e.key==='ArrowLeft')go(-1)};addEventListener('keydown',k);document.body.style.overflow='hidden';return()=>{removeEventListener('keydown',k);document.body.style.overflow=''}},[i,go]);
return <main className="pt-28 px-4 md:px-10 pb-24"><h1 className="dsp text-[clamp(64px,13vw,210px)] pb-2">Lookbook</h1><p className="lab text-bone/60 mb-8">SS26 — tap any frame</p>
<div className="grid grid-cols-12 auto-rows-[110px] md:auto-rows-[clamp(120px,17vw,250px)] gap-2 md:gap-4">{LOOKS.map((l,n)=><Reveal key={n} d={(n%3)*.08} className={`relative ${SPAN[n]}`}><button data-cursor="EXPLORE" onClick={()=>setI(n)} aria-label={`Open ${l.t}`} className="absolute inset-0 w-full overflow-hidden transition duration-700 ease-lf hover:scale-[.985]"><Frame l={l}/></button></Reveal>)}</div>
<AnimatePresence>{i!==null&&<motion.div role="dialog" aria-modal="true" aria-label="Lookbook gallery" className="fixed inset-0 z-[100] bg-ink grid grid-rows-[auto_1fr_auto]" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}>
<div className="flex justify-between p-5 lab"><span>{String(i+1).padStart(2,'0')} / {String(LOOKS.length).padStart(2,'0')}</span><button onClick={()=>setI(null)}>Close ✕</button></div>
<motion.div key={i} drag="x" dragConstraints={{left:0,right:0}} onDragEnd={(_,f)=>{if(f.offset.x<-60)go(1);if(f.offset.x>60)go(-1)}} initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} transition={{duration:.5,ease:[.16,1,.3,1]}} className="relative mx-auto w-[min(560px,92vw)] aspect-[4/5] self-center"><Frame l={LOOKS[i]} fill/></motion.div>
<div className="flex justify-between p-5 lab"><button onClick={()=>go(-1)}>← Prev</button><span>{LOOKS[i].t}</span><button onClick={()=>go(1)}>Next →</button></div></motion.div>}</AnimatePresence></main>}
