'use client';
import {useRef,useState} from 'react';import Link from 'next/link';import {home} from '@/config/home';
// Posts to Shopify's customer form: the email is saved as a Shopify customer tagged "newsletter". Only the email is collected.
export default function Newsletter(){const [s,setS]=useState<'idle'|'sending'|'sent'|'error'>('idle'),t=useRef<any>(null),d=process.env.NEXT_PUBLIC_SHOPIFY_DOMAIN,n=home.newsletter;
return <section className="bg-acid text-ink text-center px-4 py-24 md:py-36"><h2 className="dsp text-[clamp(50px,10vw,160px)]">{n.title1}<br/>{n.title2}</h2><p className="max-w-md mx-auto my-5">{n.copy}</p>
{s==='sent'?<p role="status" className="dsp text-5xl">You're in.</p>:<form action={`https://${d}/contact#contact_form`} method="post" target="lf-nl" onSubmit={()=>{setS('sending');clearTimeout(t.current);t.current=setTimeout(()=>setS(x=>x==='sending'?'error':x),12000)}} className="max-w-lg mx-auto text-left">
<div className="flex border-b-2 border-ink"><input type="hidden" name="form_type" value="customer"/><input type="hidden" name="utf8" value="✓"/><input type="hidden" name="contact[tags]" value="newsletter"/><input type="email" name="contact[email]" required autoComplete="email" placeholder="YOUR EMAIL" aria-label="Your email" className="flex-1 bg-transparent py-4 outline-none tracking-widest placeholder:text-ink/70"/><button disabled={s==='sending'} className="font-bold tracking-widest disabled:opacity-50">{s==='sending'?'…':'JOIN →'}</button></div>
<label className="flex gap-2 items-start text-sm mt-3"><input type="checkbox" required className="mt-1"/><span>I agree to receive marketing emails from LIL FREAK and can unsubscribe at any time. See our <Link href="/policies/privacy-policy" className="underline">Privacy Policy</Link>.</span></label>
{s==='error'&&<p role="alert" className="mt-3 font-bold">Couldn't sign you up right now. Please try again or email us.</p>}</form>}
<iframe name="lf-nl" title="Newsletter sign-up response" className="hidden" onLoad={()=>{if(s==='sending'){clearTimeout(t.current);setS('sent')}}}/></section>}
