'use client';
import {ReactNode,useState} from 'react';import Link from 'next/link';import {AnimatePresence,motion} from 'framer-motion';import {Plus} from 'lucide-react';import {Product} from '@/lib/shopify';import {site} from '@/config/site';
// Content comes from Shopify (description + optional metafields custom.fit / custom.material / custom.care) and /config (size chart). Empty sections are hidden.
export default function Extras({p}:{p:Product}){const [o,setO]=useState<number|null>(0),[g,setG]=useState(false),sg=site.sizeGuide;
const A=([['Description',p.description],['Fit',p.fit?.value],['Material',p.material?.value],['Care',p.care?.value]] as [string,string|undefined][]).filter(([,b])=>b).map(([t,b])=>[t,<p key={t}>{b}</p>] as [string,ReactNode]);
A.push(['Shipping & returns',<p key="s">See our <Link href="/policies/shipping-policy" className="underline">Shipping Policy</Link> and <Link href="/policies/refund-policy" className="underline">Refund Policy</Link>.</p>]);
return <>{sg.rows.length>0&&<button onClick={()=>setG(true)} className="lab underline text-fg/70 mt-4">Size guide</button>}
<div className="mt-6 border-t border-fg/15">{A.map(([t,b],i)=><div key={t} className="border-b border-fg/15"><h3><button id={`px${i}`} aria-expanded={o===i} aria-controls={`pa${i}`} onClick={()=>setO(o===i?null:i)} className="w-full flex justify-between items-center py-4 lab"><span>{t}</span><Plus size={16} className={`transition duration-500 ease-lf ${o===i?'rotate-45':''}`}/></button></h3><div id={`pa${i}`} role="region" aria-labelledby={`px${i}`} hidden={o!==i} className="text-fg/70 pb-4">{b}</div></div>)}</div>
<AnimatePresence>{g&&<motion.div className="fixed inset-0 z-[110] bg-black/70 grid place-items-center p-4" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setG(false)}><motion.div role="dialog" aria-modal="true" aria-label="Size guide" onClick={e=>e.stopPropagation()} initial={{y:40}} animate={{y:0}} exit={{y:40}} className="bg-surface w-full max-w-xl p-6 max-h-[90vh] overflow-auto"><div className="flex justify-between"><h3 className="dsp text-5xl">Size guide</h3><button onClick={()=>setG(false)} className="lab">Close ✕</button></div>
<table className="w-full text-left mt-4"><thead className="text-fg/70"><tr>{sg.head.map(h=><th key={h} className="py-2 font-normal">{h}</th>)}</tr></thead><tbody>{sg.rows.map((r,i)=><tr key={i} className="border-t border-fg/15">{r.map((c,k)=><td key={k} className="py-2">{c}</td>)}</tr>)}</tbody></table>{sg.note&&<p className="text-fg/60 text-sm mt-3">{sg.note}</p>}</motion.div></motion.div>}</AnimatePresence></>}
