'use client';
import {useState} from 'react';import {AnimatePresence,motion} from 'framer-motion';import {Plus} from 'lucide-react';import {Product} from '@/lib/shopify';
// Placeholder copy + measurements — replace with your real details
const SZ=[['XS','21"','27"','19"','8"'],['S','22"','28"','20"','8.5"'],['M','23"','29"','21"','9"'],['L','24"','30"','22"','9.5"'],['XL','25"','31"','23"','10"'],['XXL','26"','32"','24"','10.5"']];
export default function Extras({p}:{p:Product}){const [o,setO]=useState<number|null>(0),[g,setG]=useState(false);
const A:[string,string][]=[['Description',p.description||'Placeholder description.'],['Fit & sizing','Oversized fit. Model wears M. Check the size guide.'],['Material','100% heavyweight cotton · 240 GSM (placeholder).'],['Care','Machine wash cold, inside out. Do not bleach. Dry in shade.'],['Shipping','Free above ₹1,999. Delivery estimate shown at checkout.'],['Returns','Placeholder policy — add your returns terms.'],['Reviews','No reviews yet — connect a reviews app (e.g. Judge.me) to show real ratings.']];
return <><button onClick={()=>setG(true)} className="lab underline text-bone/60 mt-4">Size guide</button>
<div className="mt-6 border-t border-bone/15">{A.map(([t,b],i)=><div key={t} className="border-b border-bone/15"><button aria-expanded={o===i} onClick={()=>setO(o===i?null:i)} className="w-full flex justify-between items-center py-4 lab"><span>{t}</span><Plus size={16} className={`transition duration-500 ease-lf ${o===i?'rotate-45':''}`}/></button><div className={`grid transition-all duration-500 ease-lf ${o===i?'grid-rows-[1fr]':'grid-rows-[0fr]'}`}><div className="overflow-hidden"><p className="text-bone/60 pb-4">{b}</p></div></div></div>)}</div>
<AnimatePresence>{g&&<motion.div className="fixed inset-0 z-[110] bg-black/70 grid place-items-center p-4" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setG(false)}><motion.div role="dialog" aria-label="Size guide" onClick={e=>e.stopPropagation()} initial={{y:40}} animate={{y:0}} exit={{y:40}} transition={{duration:.5,ease:[.16,1,.3,1]}} className="bg-ink w-full max-w-xl p-6 max-h-[90vh] overflow-auto">
<div className="flex justify-between"><h3 className="dsp text-5xl">Size guide</h3><button onClick={()=>setG(false)} className="lab">Close ✕</button></div>
<svg viewBox="0 0 120 100" className="w-44 mx-auto my-4 stroke-bone fill-none" strokeWidth="1.5"><path d="M40 8l-30 16 10 20 12-6v58h56V38l12 6 10-20L80 8c-4 8-12 10-20 10S44 16 40 8z"/><path d="M22 44h76M60 18v68" strokeDasharray="3 3"/></svg>
<table className="w-full text-left"><thead className="text-bone/60"><tr>{['Size','Chest','Length','Shoulder','Sleeve'].map(h=><th key={h} className="py-2 font-normal">{h}</th>)}</tr></thead><tbody>{SZ.map(r=><tr key={r[0]} className="border-t border-bone/15">{r.map((c,i)=><td key={i} className="py-2">{c}</td>)}</tr>)}</tbody></table>
<p className="text-bone/50 text-sm mt-3">Placeholder measurements — replace with your real chart.</p></motion.div></motion.div>}</AnimatePresence></>}
