'use client';
import {useCallback,useEffect,useState} from 'react';import Image from 'next/image';import {AnimatePresence,motion} from 'framer-motion';import {Product} from '@/lib/shopify';
type M={type:'img'|'vid';src:string;alt:string;poster?:string};
export default function ProductGallery({p}:{p:Product}){
const items:M[]=[...p.images.nodes.map(i=>({type:'img' as const,src:i.url,alt:i.altText||p.title})),...p.media.nodes.filter((m:any)=>m.mediaContentType==='VIDEO'&&m.sources?.[0]).map((m:any)=>({type:'vid' as const,src:m.sources[0].url,alt:p.title,poster:m.previewImage?.url}))];
const n=items.length,[i,setI]=useState(0),[fs,setFs]=useState(false),go=useCallback((d:number)=>setI(x=>(x+d+n)%n),[n]);
useEffect(()=>{if(n<2)return;const k=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.tagName==='INPUT')return;if(e.key==='ArrowRight')go(1);if(e.key==='ArrowLeft')go(-1);if(e.key==='Escape')setFs(false)};addEventListener('keydown',k);return()=>removeEventListener('keydown',k)},[n,go]);
useEffect(()=>{document.body.style.overflow=fs?'hidden':''},[fs]);
if(!n)return <div className="relative aspect-[4/5] bg-char grid place-items-center dsp text-5xl text-bone/20">{p.title}</div>;
const m=items[i],Media=({x,contain}:{x:M;contain?:boolean})=>x.type==='vid'?<video src={x.src} poster={x.poster} controls playsInline className="absolute inset-0 w-full h-full object-cover"/>:<Image src={x.src} alt={x.alt} fill priority sizes={contain?'100vw':'(max-width:768px) 100vw,45vw'} className={contain?'object-contain':'object-cover'}/>;
return <div className="md:grid md:grid-cols-[72px_1fr] gap-3"><div className="flex md:flex-col gap-2 order-2 md:order-1 mt-2 md:mt-0 overflow-x-auto">{items.map((x,k)=><button key={k} aria-label={`Show ${x.type==='vid'?'video':'image'} ${k+1}`} onClick={()=>setI(k)} className={`relative shrink-0 w-16 aspect-[4/5] bg-char border transition ${k===i?'border-acid':'border-transparent opacity-60 hover:opacity-100'}`}>{x.type==='vid'?<span className="absolute inset-0 grid place-items-center lab">▶</span>:<Image src={x.src} alt="" fill sizes="64px" className="object-cover"/>}</button>)}</div>
<div className="order-1 md:order-2 relative aspect-[4/5] overflow-hidden bg-char"><AnimatePresence mode="wait"><motion.div key={i} className={`absolute inset-0 ${m.type==='img'?'cursor-zoom-in':''}`} initial={{opacity:0,scale:1.03}} animate={{opacity:1,scale:1}} exit={{opacity:0}} transition={{duration:.4,ease:[.16,1,.3,1]}} drag={n>1?'x':false} dragConstraints={{left:0,right:0}} onDragEnd={(_,f)=>{if(f.offset.x<-60)go(1);if(f.offset.x>60)go(-1)}} onTap={()=>m.type==='img'&&setFs(true)} data-cursor={m.type==='img'?'EXPLORE':undefined}><Media x={m}/></motion.div></AnimatePresence>
{n>1&&<span className="absolute bottom-3 left-3 lab bg-ink/70 px-2 py-1">{i+1} / {n}</span>}</div>
<AnimatePresence>{fs&&<motion.div role="dialog" aria-modal="true" aria-label="Zoomed image" className="fixed inset-0 z-[150] bg-ink" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><div className="absolute inset-4 md:inset-10"><Media x={m} contain/></div>
<button onClick={()=>setFs(false)} className="absolute top-4 right-5 lab z-10">Close ✕</button>{n>1&&<><button aria-label="Previous" onClick={()=>go(-1)} className="absolute left-4 top-1/2 lab z-10">←</button><button aria-label="Next" onClick={()=>go(1)} className="absolute right-4 top-1/2 lab z-10">→</button></>}<span className="absolute top-4 left-5 lab z-10">{i+1} / {n}</span></motion.div>}</AnimatePresence></div>}
