'use client';
import {useEffect,useRef,useState} from 'react';import Link from 'next/link';import Image from 'next/image';import {AnimatePresence,motion} from 'framer-motion';import {X} from 'lucide-react';import {Product,searchProducts,getProducts,inr} from '@/lib/shopify';
export default function SearchOverlay(){const [o,setO]=useState(false),[q,setQ]=useState(''),[r,setR]=useState<Product[]>([]),[tr,setTr]=useState<Product[]>([]),[rec,setRec]=useState<string[]>([]),[load,setLoad]=useState(false),ref=useRef<HTMLInputElement>(null);
useEffect(()=>{const f=()=>{setO(true);setTimeout(()=>ref.current?.focus(),100);try{setRec(JSON.parse(localStorage.getItem('lf_recent')||'[]'))}catch{}};const k=(e:KeyboardEvent)=>e.key==='Escape'&&setO(false);addEventListener('lf-search',f);addEventListener('keydown',k);return()=>{removeEventListener('lf-search',f);removeEventListener('keydown',k)}},[]);
useEffect(()=>{if(o&&!tr.length)getProducts().then(p=>setTr(p.slice(0,4))).catch(()=>{})},[o,tr.length]);
useEffect(()=>{if(q.trim().length<2){setR([]);return}setLoad(true);const t=setTimeout(()=>searchProducts(q.trim()).then(setR).catch(()=>setR([])).finally(()=>setLoad(false)),300);return()=>clearTimeout(t)},[q]);
const done=()=>{try{if(q.trim())localStorage.setItem('lf_recent',JSON.stringify([q.trim(),...rec.filter(x=>x!==q.trim())].slice(0,5)))}catch{}setO(false)};
const Item=({p}:{p:Product})=><Link href={`/product/${p.handle}`} onClick={done} className="flex gap-3 items-center py-2 hover:text-acid"><span className="relative w-14 aspect-[4/5] bg-char shrink-0">{p.images.nodes[0]&&<Image src={p.images.nodes[0].url} alt="" fill sizes="56px" className="object-cover"/>}</span><span className="flex-1">{p.title}</span><span>{inr(p.priceRange.minVariantPrice.amount)}</span></Link>;
return <AnimatePresence>{o&&<motion.div role="dialog" aria-modal="true" aria-label="Search" className="fixed inset-0 z-[120] bg-ink overflow-auto px-4 md:px-10 py-6" initial={{opacity:0,y:-30}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-30}} transition={{duration:.5,ease:[.16,1,.3,1]}}>
<div className="flex justify-end"><button aria-label="Close search" onClick={()=>setO(false)}><X/></button></div>
<h2 className="dsp text-[clamp(44px,9vw,140px)] mt-6">What are you<br/>looking for?</h2>
<input ref={ref} value={q} onChange={e=>setQ(e.target.value)} placeholder="Search tees, hoodies, sweats…" aria-label="Search" className="w-full bg-transparent border-b-2 border-bone py-4 text-2xl outline-none focus:border-acid my-8"/>
{q.trim().length>=2?<div className="max-w-2xl">{load?<p className="text-bone/60">Searching…</p>:r.length?r.map(p=><Item key={p.id} p={p}/>):<div><h3 className="dsp text-5xl mb-3">Nothing found.</h3><p className="text-bone/60">Try “tee”, “hoodie” or browse <Link href="/shop" onClick={done} className="underline">everything</Link>.</p></div>}</div>
:<div className="grid md:grid-cols-3 gap-10"><div><h3 className="lab text-bone/60 mb-3">Trending</h3>{tr.map(p=><Item key={p.id} p={p}/>)}</div><div><h3 className="lab text-bone/60 mb-3">Categories</h3>{[['Tees','/category/tees'],['Hoodies','/category/hoodies'],['Sweats','/category/sweats'],['New drop','/new-drop']].map(([n,h])=><Link key={h} href={h} onClick={done} className="dsp text-4xl block hover:text-acid">{n}</Link>)}</div><div><h3 className="lab text-bone/60 mb-3">Recent</h3>{rec.length?rec.map(x=><button key={x} onClick={()=>setQ(x)} className="block py-1 hover:text-acid">{x}</button>):<p className="text-bone/50">No recent searches.</p>}</div></div>}
</motion.div>}</AnimatePresence>}
