import {notFound} from 'next/navigation';import {getPolicy} from '@/lib/shopify';import {site} from '@/config/site';import {page} from '@/lib/seo';
export const dynamicParams=false;
const M:Record<string,{title:string;key?:'privacyPolicy'|'refundPolicy'|'shippingPolicy'|'termsOfService'}>={'privacy-policy':{title:'Privacy Policy',key:'privacyPolicy'},'terms-of-service':{title:'Terms of Service',key:'termsOfService'},'refund-policy':{title:'Refund Policy',key:'refundPolicy'},'shipping-policy':{title:'Shipping Policy',key:'shippingPolicy'},'cookie-policy':{title:'Cookie Policy'}};
export const generateStaticParams=()=>Object.keys(M).map(slug=>({slug}));
export const generateMetadata=({params}:{params:{slug:string}})=>M[params.slug]?page(M[params.slug].title,`/policies/${params.slug}`):{};
export default async function P({params}:{params:{slug:string}}){const m=M[params.slug];if(!m)notFound();const pol=m.key?await getPolicy(m.key):null,u=site.policyUpdated[params.slug];
return <main className="pt-10 px-4 md:px-10 pb-24 min-h-screen"><h1 className="dsp text-[clamp(50px,9vw,140px)] pb-4">{m.title}</h1>{u&&<p className="lab text-fg/60 mb-8">Last updated: {u}</p>}
<article className="max-w-3xl leading-relaxed [&_h2]:text-2xl [&_h2]:mt-8 [&_h2]:mb-2 [&_h3]:text-xl [&_h3]:mt-6 [&_p]:my-3 [&_ul]:list-disc [&_ul]:pl-6 [&_a]:underline">
{m.key?(pol?.body?<div dangerouslySetInnerHTML={{__html:pol.body}}/>:<p className="text-fg/70">This policy hasn't been published yet. Owner: add it in Shopify admin → Settings → Policies.</p>):
<><p>This site stores only what is needed for the shop to work, in your browser&apos;s local storage: <code>lf_cart</code> (your bag ID), <code>lf_wish</code> (wishlist), <code>lf_recent</code> (recent searches), <code>lf_theme</code> (light/dark choice), <code>lf_consent</code> (that you dismissed the notice). Campaign tags (utm_*) are kept for the browser session only, to pass to checkout.</p><p>Checkout and customer accounts are provided by Shopify on its own pages, which set their own cookies — see the Privacy Policy.</p><p>We do not use advertising, analytics or tracking cookies. If this changes, this policy will be updated and consent requested first.</p><p>Questions: {site.email}</p></>}</article></main>}
